import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Hypercerts API</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        style={{
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          alignItems: "center",
          height: "100vh",
          width: "100vw",
          backgroundColor: "#304949",
        }}
      >
        <h1 className={inter.className} style={{ color: "#fff" }}>
          Hypercerts API
        </h1>

        <Image
          src="/hc_logo_400_400.png"
          alt="Hypercerts logo"
          width={400}
          height={400}
          priority
        />
      </main>
    </>
  );
}
